name: 'Setup Bun Environment'

description: 'Setup Bun environment with caching'
inputs:
  bun-version:
    description: 'Bun version to install'
    required: false
    default: '1.3.0'

runs:
  using: 'composite'
  steps:
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}

    - uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: bun-cache-${{ runner.os }}-${{ hashFiles('bun.lock') }}

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile
