name: Basic CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-bun
      - name: Lint
        run: bun run lint

  build-test:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-bun
      - name: Build
        run: bun run build

  test:
    name: Test
    services:
      redis:
        image: redis:7
        ports:
          - 16379:6379
        env:
          REDIS_PASSWORD: redis
      postgres:
        image: postgres:16
        ports:
          - 15432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-bun
      - name: Prepare Database
        run: bun run db:migrate
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:15432/postgres
      - name: Test
        run: bun test

  # FIXME: add drizzle generation diff check

  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-bun
      - name: Type Check
        run: bun run typecheck
