name: Basic CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-bun
      - name: Lint
        run: bun run lint

  build-test:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-bun
      - name: Build
        run: bun build
  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-bun
      - name: Type Check
        run: bun run typecheck
